### ISSUE TITLE
Error: spawn phantomjs ENOENT

### ISSUE THREAD

**Issue by zeke** [juliangruber/phantomjs-stream#8]
Trying to find the root cause of https://github.com/juliangruber/browser-run/issues/102

```
~/forks/phantomjs-stream master 6s
❯ npm t

> phantomjs-stream@1.1.1 test /Users/zeke/forks/phantomjs-stream
> make test

TAP version 13
# execute
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
make: *** [test] Error 1
npm ERR! Test failed.  See above for more details.

~/forks/phantomjs-stream master
❯ node -v
v5.10.1
```

**Comment by ganeshpaiya** [comment]
I am also facing the same issue, it is working fine in local but in linux server not working buffer output value gives as a spawn /var/projects/dev/facommtrack/node_modules/phantomjs-prebuilt/lib/phantom\bin\phantomjs.exe ENOENT
